# Generated by Django 5.1.5 on 2025-02-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_course_student_remove_order_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Student',
            new_name='student',
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
