# Generated by Django 5.1.5 on 2025-02-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_student_enrollment_student_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
